[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = true
fileWatcherType = "poll"  # <--- MUDANÃ‡A AQUI: Garante o reload em Dev Containers

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
